language: java

after_success:
  - python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)

#deploy:
#  provider: gae
#  config: "src/main/webapp/WEB-INF/appengine-web.xml"
#  keyfile: timeclicker-fb0e526f9f9f.json
#  default: true
#  project: timeclicker-1079
#
#before_install:
#- openssl aes-256-cbc -K $encrypted_2bd92e616da3_key -iv $encrypted_2bd92e616da3_iv
#  -in timeclicker-fb0e526f9f9f.json.enc -out timeclicker-fb0e526f9f9f.json -d
