language: java
jdk:
  - oraclejdk8
sudo: false
install: true

addons:
  sonarqube:
    organization: "moritanosuke-github"
    token:
      secure: "F8D0gMee0UkDgM8oy+uAIpZqyJUoTTTky6WFrZg0UlKEyYXn9W7/mZPYvtZmSE/rXu3Rp2JpPWvB8Vmt0u9hQ8jf5va1mVXE/yoJxCzS2LPn8JCLUlIRzD4g91Bbfasx4BH4qK8zwa3PFVXwm6xi6drTHYQWiF41tvvuQiPSXJqVB/RAgbC/3amUXlmj++i1kD8Nbn4DOpQWdHlLwzehgy+XesKdoVdafGKXhzGBbERes4MKvqo0YslX5N22oOPLcWL8ePpLs7lcgTTi5a4GjXh5G3RkeoRNs3iZReXJ02lQXP5fotgG27WutLallbyngWahORlbpTref8CAz7Hr5vDXHr0kKakxfB4TyGA0M4YJf/cinY/dXInkMMmTFDMz4lYadFVb3P0V6pjEMyRjaJhrC3KUDfe94QwBq5DitSvumcMtCeoUdj0KYwC67jo+1GT8kWvC2u1OHuv1TD5LIbiXosemNlfykGIKv+vUY6jXv4Azj2h4+sOtNaB4Effc0n4ARrYSYRtpfaZy30wqt49jxRaXFeDDsFxhnwDPgOnkzwmMxOKPGdTeKVXFFAhijAs85P6WtJF+HVvs5tqhMLPlTexEOhjvLwo3g2VaX829Lp+niuX75KePFdpud+1kZnUXlQChFS/vyXb6J2Y0l0VD7vGY8etWEgp8gvlMb5w="

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

# disabled because of https://github.com/travis-ci/dpl/issues/389
#deploy:
#  provider: gae
#  config: "src/main/webapp/WEB-INF/appengine-web.xml"
#  keyfile: timeclicker-fb0e526f9f9f.json
#  default: true
#  project: timeclicker-1079
#
#before_install:
#  - openssl aes-256-cbc -K $encrypted_2bd92e616da3_key -iv $encrypted_2bd92e616da3_iv -in timeclicker-fb0e526f9f9f.json.enc -out timeclicker-fb0e526f9f9f.json -d
