language: java

deploy:
  provider: gae
  keyfile: timeclicker-fb0e526f9f9f.json
  default: true
  project: timeclicker-1079

before_install:
- openssl aes-256-cbc -K $encrypted_2bd92e616da3_key -iv $encrypted_2bd92e616da3_iv
  -in timeclicker-fb0e526f9f9f.json.enc -out timeclicker-fb0e526f9f9f.json -d
